plugins {
    id 'java'
}

group = 'com.github.thejavalistener'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {

    // SPRING - sólo lo necesario para inyección de dependencias
    implementation 'org.springframework:spring-context:5.3.14'
    implementation 'org.springframework:spring-context-support:5.3.14'
    implementation 'com.github.thejavalistener:MyFwkUtils:1.0.0'
    
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
