plugins {
    id 'java-library'
}


group = 'com.github.thejavalistener'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    api 'com.github.thejavalistener:MyFwkBackend' //:1.1.0'
    api 'com.github.thejavalistener:MyFwkUtils'   //:1.0.0'
}
   

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
